directories:
  output: release
  buildResources: build
appId: com.vibe.musicplayer
productName: Vibe
files:
  - filter:
      - dist/**/*
      - src/index.html
      - src/assets/**/*
linux:
  target:
    - AppImage
    - deb
    - rpm
  icon: src/assets/icon.png
  category: Audio
  maintainer: Anthony
win:
  target:
    - nsis
    - portable
  icon: src/assets/icon.png
mac:
  target:
    - dmg
  icon: src/assets/icon.png
  category: public.app-category.music
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
electronVersion: 27.3.11
